// Source icon definitions derived from Lucide (https://github.com/lucide-icons/lucide).
// Lucide is licensed under the ISC license.
// AUTO-GENERATED by scripts/build_icons.ts — DO NOT EDIT

export type IconName =
  | 'check'
  | 'x'
  | 'chevron-down'
  | 'chevron-up'
  | 'chevron-left'
  | 'chevron-right'
  | 'plus'
  | 'minus'
  | 'search'
  | 'menu'
  | 'settings'
  | 'info'
  | 'alert-triangle'
  | 'arrow-left'
  | 'arrow-right'
  | 'trash';

export type IconPathCommand =
  | { op: 'M' | 'L'; x: number; y: number }
  | { op: 'C'; c1x: number; c1y: number; c2x: number; c2y: number; x: number; y: number }
  | { op: 'Q'; cx: number; cy: number; x: number; y: number }
  | { op: 'A'; cx: number; cy: number; r: number; start: number; end: number; ccw?: boolean }
  | { op: 'Z' };

export const ICON_PATHS: Record<IconName, IconPathCommand[]> = {
  check: [
    { op: 'M', x: 20, y: 6 },
    { op: 'L', x: 9, y: 17 },
    { op: 'L', x: 4, y: 12 },
  ],
  x: [
    { op: 'M', x: 18, y: 6 },
    { op: 'L', x: 6, y: 18 },
    { op: 'M', x: 6, y: 6 },
    { op: 'L', x: 18, y: 18 },
  ],
  'chevron-down': [
    { op: 'M', x: 6, y: 9 },
    { op: 'L', x: 12, y: 15 },
    { op: 'L', x: 18, y: 9 },
  ],
  'chevron-up': [
    { op: 'M', x: 18, y: 15 },
    { op: 'L', x: 12, y: 9 },
    { op: 'L', x: 6, y: 15 },
  ],
  'chevron-left': [
    { op: 'M', x: 15, y: 18 },
    { op: 'L', x: 9, y: 12 },
    { op: 'L', x: 15, y: 6 },
  ],
  'chevron-right': [
    { op: 'M', x: 9, y: 18 },
    { op: 'L', x: 15, y: 12 },
    { op: 'L', x: 9, y: 6 },
  ],
  plus: [
    { op: 'M', x: 5, y: 12 },
    { op: 'L', x: 19, y: 12 },
    { op: 'M', x: 12, y: 5 },
    { op: 'L', x: 12, y: 19 },
  ],
  minus: [
    { op: 'M', x: 5, y: 12 },
    { op: 'L', x: 19, y: 12 },
  ],
  search: [
    { op: 'M', x: 21, y: 21 },
    { op: 'L', x: 16.66, y: 16.66 },
    { op: 'M', x: 11, y: 19 },
    { op: 'A', cx: 11, cy: 11, r: 8, start: 1.570796, end: 4.712389 },
    { op: 'A', cx: 11, cy: 11, r: 8, start: -1.570796, end: 1.570796 },
  ],
  menu: [
    { op: 'M', x: 4, y: 5 },
    { op: 'L', x: 20, y: 5 },
    { op: 'M', x: 4, y: 12 },
    { op: 'L', x: 20, y: 12 },
    { op: 'M', x: 4, y: 19 },
    { op: 'L', x: 20, y: 19 },
  ],
  settings: [
    { op: 'M', x: 9.671, y: 4.136 },
    { op: 'A', cx: 12.0005, cy: 4.357427, r: 2.34, start: -3.046824, end: -0.094769 },
    { op: 'A', cx: 16.660902, cy: 3.929854, r: 2.34, start: 3.053382, end: 1.134855, ccw: true },
    { op: 'A', cx: 18.616354, cy: 8.181687, r: 2.34, start: -1.99698, end: 0.949208 },
    { op: 'A', cx: 21.323046, cy: 11.9995, r: 2.34, start: -2.182641, end: -4.100544, ccw: true },
    { op: 'A', cx: 18.616354, cy: 15.817313, r: 2.34, start: -0.949208, end: 1.99698 },
    { op: 'A', cx: 16.660902, cy: 20.069146, r: 2.34, start: -1.134855, end: -3.053382, ccw: true },
    { op: 'A', cx: 12.0005, cy: 19.641573, r: 2.34, start: 0.094769, end: 3.046824 },
    { op: 'A', cx: 7.340059, cy: 20.068699, r: 2.34, start: -0.088019, end: -2.007191, ccw: true },
    { op: 'A', cx: 5.383646, cy: 15.817313, r: 2.34, start: 1.144613, end: 4.0908 },
    { op: 'A', cx: 2.676954, cy: 11.9995, r: 2.34, start: 0.958951, end: -0.958951, ccw: true },
    { op: 'A', cx: 5.385365, cy: 8.182919, r: 2.34, start: 2.193289, end: 5.137297 },
    { op: 'A', cx: 7.338098, cy: 3.929854, r: 2.34, start: 2.006738, end: 0.088211, ccw: true },
    { op: 'M', x: 12, y: 15 },
    { op: 'A', cx: 12, cy: 12, r: 3, start: 1.570796, end: 4.712389 },
    { op: 'A', cx: 12, cy: 12, r: 3, start: -1.570796, end: 1.570796 },
  ],
  info: [
    { op: 'M', x: 12, y: 22 },
    { op: 'A', cx: 12, cy: 12, r: 10, start: 1.570796, end: 4.712389 },
    { op: 'A', cx: 12, cy: 12, r: 10, start: -1.570796, end: 1.570796 },
    { op: 'M', x: 12, y: 16 },
    { op: 'L', x: 12, y: 12 },
    { op: 'M', x: 12, y: 8 },
    { op: 'L', x: 12.01, y: 8 },
  ],
  'alert-triangle': [
    { op: 'M', x: 21.73, y: 18 },
    { op: 'L', x: 13.73, y: 4 },
    { op: 'A', cx: 11.99, cy: 4.986103, r: 2, start: -0.515594, end: -2.625999, ccw: true },
    { op: 'L', x: 2.25, y: 18 },
    { op: 'A', cx: 3.982004, cy: 19.000081, r: 2, start: -2.617947, end: -4.721387, ccw: true },
    { op: 'L', x: 20, y: 21 },
    { op: 'A', cx: 19.99795, cy: 19.000001, r: 2, start: 1.569771, end: -0.523599, ccw: true },
    { op: 'M', x: 12, y: 9 },
    { op: 'L', x: 12, y: 13 },
    { op: 'M', x: 12, y: 17 },
    { op: 'L', x: 12.01, y: 17 },
  ],
  'arrow-left': [
    { op: 'M', x: 12, y: 19 },
    { op: 'L', x: 5, y: 12 },
    { op: 'L', x: 12, y: 5 },
    { op: 'M', x: 19, y: 12 },
    { op: 'L', x: 5, y: 12 },
  ],
  'arrow-right': [
    { op: 'M', x: 5, y: 12 },
    { op: 'L', x: 19, y: 12 },
    { op: 'M', x: 12, y: 5 },
    { op: 'L', x: 19, y: 12 },
    { op: 'L', x: 12, y: 19 },
  ],
  trash: [
    { op: 'M', x: 19, y: 6 },
    { op: 'L', x: 19, y: 20 },
    { op: 'A', cx: 17, cy: 20, r: 2, start: 0, end: 1.570796 },
    { op: 'L', x: 7, y: 22 },
    { op: 'A', cx: 7, cy: 20, r: 2, start: 1.570796, end: 3.141593 },
    { op: 'L', x: 5, y: 6 },
    { op: 'M', x: 3, y: 6 },
    { op: 'L', x: 21, y: 6 },
    { op: 'M', x: 8, y: 6 },
    { op: 'L', x: 8, y: 4 },
    { op: 'A', cx: 10, cy: 4, r: 2, start: 3.141593, end: 4.712389 },
    { op: 'L', x: 14, y: 2 },
    { op: 'A', cx: 14, cy: 4, r: 2, start: -1.570796, end: 0 },
    { op: 'L', x: 16, y: 6 },
  ],
};
