#!/usr/bin/env bun
// Source icon definitions derived from Lucide (https://github.com/lucide-icons/lucide).
// Lucide is licensed under the ISC license.

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

type IconName =
  | 'check'
  | 'x'
  | 'chevron-down'
  | 'chevron-up'
  | 'chevron-left'
  | 'chevron-right'
  | 'plus'
  | 'minus'
  | 'search'
  | 'menu'
  | 'settings'
  | 'info'
  | 'alert-triangle'
  | 'arrow-left'
  | 'arrow-right'
  | 'trash';

type IconPathCommand =
  | { op: 'M' | 'L'; x: number; y: number }
  | { op: 'C'; c1x: number; c1y: number; c2x: number; c2y: number; x: number; y: number }
  | { op: 'Q'; cx: number; cy: number; x: number; y: number }
  | { op: 'A'; cx: number; cy: number; r: number; start: number; end: number; ccw?: boolean }
  | { op: 'Z' };

const ICON_NAMES: readonly IconName[] = [
  'check',
  'x',
  'chevron-down',
  'chevron-up',
  'chevron-left',
  'chevron-right',
  'plus',
  'minus',
  'search',
  'menu',
  'settings',
  'info',
  'alert-triangle',
  'arrow-left',
  'arrow-right',
  'trash',
];

const ICON_SOURCES: Record<IconName, readonly string[]> = {
  check: ['M20 6 9 17l-5-5'],
  x: ['M18 6 6 18', 'm6 6 12 12'],
  'chevron-down': ['m6 9 6 6 6-6'],
  'chevron-up': ['m18 15-6-6-6 6'],
  'chevron-left': ['m15 18-6-6 6-6'],
  'chevron-right': ['m9 18 6-6-6-6'],
  plus: ['M5 12h14', 'M12 5v14'],
  minus: ['M5 12h14'],
  search: ['m21 21-4.34-4.34', 'M11 19a8 8 0 1 1 0-16a8 8 0 1 1 0 16'],
  menu: ['M4 5h16', 'M4 12h16', 'M4 19h16'],
  settings: [
    'M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915',
    'M12 15a3 3 0 1 1 0-6a3 3 0 1 1 0 6',
  ],
  info: ['M12 22a10 10 0 1 1 0-20a10 10 0 1 1 0 20', 'M12 16v-4', 'M12 8h.01'],
  'alert-triangle': [
    'm21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3',
    'M12 9v4',
    'M12 17h.01',
  ],
  'arrow-left': ['m12 19-7-7 7-7', 'M19 12H5'],
  'arrow-right': ['M5 12h14', 'm12 5 7 7-7 7'],
  trash: [
    'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6',
    'M3 6h18',
    'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2',
  ],
};

type Token = { kind: 'command'; value: string } | { kind: 'number'; value: number };

type Cursor = { x: number; y: number };

function main(): Promise<void> {
  const outputPath = fileURLToPath(new URL('../src/components/icons.ts', import.meta.url));
  const commands = Object.fromEntries(
    ICON_NAMES.map((name) => [name, ICON_SOURCES[name].flatMap((d) => parsePathData(d))]),
  ) as Record<IconName, IconPathCommand[]>;
  return writeFile(outputPath, renderOutput(commands));
}

function renderOutput(commands: Record<IconName, IconPathCommand[]>): string {
  const lines: string[] = [
    '// biome-ignore-all format: generated file',
    '// Source icon definitions derived from Lucide (https://github.com/lucide-icons/lucide).',
    '// Lucide is licensed under the ISC license.',
    '// AUTO-GENERATED by scripts/build_icons.ts — DO NOT EDIT',
    '',
    'export type IconName =',
    ...ICON_NAMES.map(
      (name, index) => `  | '${name}'${index === ICON_NAMES.length - 1 ? ';' : ''}`,
    ),
    '',
    'export type IconPathCommand =',
    "  | { op: 'M' | 'L'; x: number; y: number }",
    "  | { op: 'C'; c1x: number; c1y: number; c2x: number; c2y: number; x: number; y: number }",
    "  | { op: 'Q'; cx: number; cy: number; x: number; y: number }",
    "  | { op: 'A'; cx: number; cy: number; r: number; start: number; end: number; ccw?: boolean }",
    "  | { op: 'Z' };",
    '',
    'export const ICON_PATHS: Record<IconName, IconPathCommand[]> = {',
  ];

  for (const name of ICON_NAMES) {
    lines.push(`  '${name}': [`);
    for (const command of commands[name]) {
      lines.push(`    ${formatCommand(command)},`);
    }
    lines.push('  ],');
  }

  lines.push('};', '');
  return lines.join('\n');
}

function formatCommand(command: IconPathCommand): string {
  switch (command.op) {
    case 'M':
    case 'L':
      return `{ op: '${command.op}', x: ${formatNumber(command.x)}, y: ${formatNumber(command.y)} }`;
    case 'C':
      return `{
      op: 'C',
      c1x: ${formatNumber(command.c1x)},
      c1y: ${formatNumber(command.c1y)},
      c2x: ${formatNumber(command.c2x)},
      c2y: ${formatNumber(command.c2y)},
      x: ${formatNumber(command.x)},
      y: ${formatNumber(command.y)},
    }`.replace(/\n\s+/g, ' ');
    case 'Q':
      return `{
      op: 'Q',
      cx: ${formatNumber(command.cx)},
      cy: ${formatNumber(command.cy)},
      x: ${formatNumber(command.x)},
      y: ${formatNumber(command.y)},
    }`.replace(/\n\s+/g, ' ');
    case 'A':
      return `{ op: 'A', cx: ${formatNumber(command.cx)}, cy: ${formatNumber(command.cy)}, r: ${formatNumber(command.r)}, start: ${formatNumber(command.start)}, end: ${formatNumber(command.end)}${command.ccw === true ? ', ccw: true' : ''} }`;
    case 'Z':
      return "{ op: 'Z' }";
  }
}

function formatNumber(value: number): string {
  const normalized = Math.abs(value) < 1e-9 ? 0 : Number(value.toFixed(6));
  return Number.isInteger(normalized) ? String(normalized) : String(normalized);
}

function parsePathData(d: string): IconPathCommand[] {
  const tokens = tokenize(d);
  const commands: IconPathCommand[] = [];
  let index = 0;
  let current: string | null = null;
  let cursor: Cursor = { x: 0, y: 0 };
  let subpathStart: Cursor = { x: 0, y: 0 };

  const nextNumber = (): number => {
    const token = tokens[index];
    if (!token || token.kind !== 'number')
      throw new Error(`expected number in path ${JSON.stringify(d)}`);
    ++index;
    return token.value;
  };
  const hasNumber = (): boolean => tokens[index]?.kind === 'number';

  while (index < tokens.length) {
    const token = tokens[index];
    if (token.kind === 'command') {
      current = token.value;
      ++index;
    } else if (current === null) {
      throw new Error(`path ${JSON.stringify(d)} starts without a command`);
    }
    if (current === null) break;

    switch (current) {
      case 'M':
      case 'm': {
        let isFirst = true;
        while (hasNumber()) {
          const point = resolvePoint(current, cursor, nextNumber(), nextNumber());
          if (isFirst) {
            commands.push({ op: 'M', x: point.x, y: point.y });
            subpathStart = point;
            isFirst = false;
          } else {
            commands.push({ op: 'L', x: point.x, y: point.y });
          }
          cursor = point;
        }
        break;
      }
      case 'L':
      case 'l': {
        while (hasNumber()) {
          cursor = resolvePoint(current, cursor, nextNumber(), nextNumber());
          commands.push({ op: 'L', x: cursor.x, y: cursor.y });
        }
        break;
      }
      case 'H':
      case 'h': {
        while (hasNumber()) {
          const value = nextNumber();
          cursor = { x: current === 'h' ? cursor.x + value : value, y: cursor.y };
          commands.push({ op: 'L', x: cursor.x, y: cursor.y });
        }
        break;
      }
      case 'V':
      case 'v': {
        while (hasNumber()) {
          const value = nextNumber();
          cursor = { x: cursor.x, y: current === 'v' ? cursor.y + value : value };
          commands.push({ op: 'L', x: cursor.x, y: cursor.y });
        }
        break;
      }
      case 'C':
      case 'c': {
        while (hasNumber()) {
          const c1 = resolvePoint(current, cursor, nextNumber(), nextNumber());
          const c2 = resolvePoint(current, cursor, nextNumber(), nextNumber());
          const end = resolvePoint(current, cursor, nextNumber(), nextNumber());
          commands.push({
            op: 'C',
            c1x: c1.x,
            c1y: c1.y,
            c2x: c2.x,
            c2y: c2.y,
            x: end.x,
            y: end.y,
          });
          cursor = end;
        }
        break;
      }
      case 'Q':
      case 'q': {
        while (hasNumber()) {
          const control = resolvePoint(current, cursor, nextNumber(), nextNumber());
          const end = resolvePoint(current, cursor, nextNumber(), nextNumber());
          commands.push({ op: 'Q', cx: control.x, cy: control.y, x: end.x, y: end.y });
          cursor = end;
        }
        break;
      }
      case 'A':
      case 'a': {
        while (hasNumber()) {
          const rx = nextNumber();
          const ry = nextNumber();
          const rotation = nextNumber();
          const largeArc = nextNumber();
          const sweep = nextNumber();
          const end = resolvePoint(current, cursor, nextNumber(), nextNumber());
          const arc = svgArcToCenter(
            cursor.x,
            cursor.y,
            end.x,
            end.y,
            rx,
            ry,
            rotation,
            largeArc,
            sweep,
            d,
          );
          if (arc === null) {
            commands.push({ op: 'L', x: end.x, y: end.y });
          } else {
            commands.push(arc);
          }
          cursor = end;
        }
        break;
      }
      case 'Z':
      case 'z': {
        commands.push({ op: 'Z' });
        cursor = subpathStart;
        break;
      }
      default:
        throw new Error(
          `unsupported SVG path command ${JSON.stringify(current)} in ${JSON.stringify(d)}`,
        );
    }
  }

  if (commands.length === 0) throw new Error(`empty icon path ${JSON.stringify(d)}`);
  return commands;
}

function resolvePoint(command: string, cursor: Cursor, x: number, y: number): Cursor {
  if (command === command.toLowerCase()) return { x: cursor.x + x, y: cursor.y + y };
  return { x, y };
}

function tokenize(d: string): Token[] {
  const tokens: Token[] = [];
  let index = 0;
  while (index < d.length) {
    const ch = d[index];
    if (ch === ' ' || ch === '\t' || ch === '\n' || ch === '\r' || ch === ',') {
      ++index;
      continue;
    }
    if (/[A-Za-z]/.test(ch)) {
      if (!/[AaCcHhLlMmQqVvZz]/.test(ch)) {
        throw new Error(
          `unsupported SVG path command ${JSON.stringify(ch)} in ${JSON.stringify(d)}`,
        );
      }
      tokens.push({ kind: 'command', value: ch });
      ++index;
      continue;
    }
    const match = /^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?/.exec(d.slice(index));
    if (!match)
      throw new Error(`failed to parse SVG path data near ${JSON.stringify(d.slice(index))}`);
    tokens.push({ kind: 'number', value: Number(match[0]) });
    index += match[0].length;
  }
  return tokens;
}

function svgArcToCenter(
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  rx: number,
  ry: number,
  rotation: number,
  largeArcFlag: number,
  sweepFlag: number,
  source: string,
): IconPathCommand | null {
  if (!Number.isFinite(rx) || !Number.isFinite(ry))
    throw new Error(`invalid arc radii in ${JSON.stringify(source)}`);
  if (rx === 0 || ry === 0) return null;
  if (Math.abs(rx) !== Math.abs(ry)) {
    throw new Error(`non-circular arc unsupported in ${JSON.stringify(source)}`);
  }
  const phi = ((rotation % 360) * Math.PI) / 180;
  if (Math.abs(phi) > 1e-9) {
    throw new Error(`rotated arc unsupported in ${JSON.stringify(source)}`);
  }
  if (x1 === x2 && y1 === y2) return null;

  const r = Math.abs(rx);
  const dx = (x1 - x2) / 2;
  const dy = (y1 - y2) / 2;
  let scaledRadius = r;
  const lambda = (dx * dx + dy * dy) / (scaledRadius * scaledRadius);
  if (lambda > 1) scaledRadius *= Math.sqrt(lambda);

  const numerator = scaledRadius * scaledRadius - dx * dx - dy * dy;
  const denom = dx * dx + dy * dy;
  const root = denom === 0 ? 0 : Math.sqrt(Math.max(0, numerator / denom));
  const sign = largeArcFlag === sweepFlag ? -1 : 1;
  const cxp = sign * root * dy;
  const cyp = sign * root * -dx;
  const cx = cxp + (x1 + x2) / 2;
  const cy = cyp + (y1 + y2) / 2;

  const ux = (dx - cxp) / scaledRadius;
  const uy = (dy - cyp) / scaledRadius;
  const vx = (-dx - cxp) / scaledRadius;
  const vy = (-dy - cyp) / scaledRadius;
  const start = angleBetween(1, 0, ux, uy);
  let delta = angleBetween(ux, uy, vx, vy);
  if (sweepFlag === 0 && delta > 0) delta -= Math.PI * 2;
  if (sweepFlag === 1 && delta < 0) delta += Math.PI * 2;
  const end = start + delta;

  return {
    op: 'A',
    cx,
    cy,
    r: scaledRadius,
    start,
    end,
    ...(delta < 0 ? { ccw: true } : {}),
  };
}

function angleBetween(ux: number, uy: number, vx: number, vy: number): number {
  const dot = ux * vx + uy * vy;
  const det = ux * vy - uy * vx;
  return Math.atan2(det, dot);
}

await main();
