#!/usr/bin/env python3
"""Embed a binary file as a C++ ``unsigned char[]`` literal.

Used at configure time to bake assets (fonts, etc.) into the binary without
shelling out to ``xxd`` / ``objcopy`` (which aren't reliably available across
all supported toolchains).

Usage:
    embed_binary.py --input PATH --output PATH --namespace NS --variable VAR

The generated translation unit has the shape::

    namespace NS {
      extern const unsigned char VAR[];
      extern const unsigned long long VAR_size;
    }
    const unsigned char NS::VAR[] = { 0x.., ... };
    const unsigned long long NS::VAR_size = N;

The corresponding header is the caller's responsibility (kept hand-written so
the public surface stays under ``include/fxe/...``).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def emit(input_path: Path, output_path: Path, namespace: str, variable: str) -> None:
    data = input_path.read_bytes()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build the byte literal as 16-per-line chunks for diffability and to keep
    # line lengths sane. ~600 KB output for a 2.5 MB input.
    chunks: list[str] = []
    line: list[str] = []
    for b in data:
        line.append(f"0x{b:02x}")
        if len(line) == 16:
            chunks.append(",".join(line))
            line = []
    if line:
        chunks.append(",".join(line))
    body = ",\n  ".join(chunks)

    tmp = output_path.with_suffix(output_path.suffix + ".tmp")
    tmp.write_text(
        "// AUTO-GENERATED by scripts/embed_binary.py — DO NOT EDIT\n"
        f"// Source: {input_path.name}\n"
        f"// Bytes:  {len(data)}\n"
        "\n"
        f"namespace {namespace} {{\n"
        f"  extern const unsigned char {variable}[];\n"
        f"  extern const unsigned long long {variable}_size;\n"
        "}\n"
        "\n"
        f"const unsigned char {namespace}::{variable}[] = {{\n"
        f"  {body}\n"
        "};\n"
        f"const unsigned long long {namespace}::{variable}_size = {len(data)};\n",
    )

    # Atomic-ish rename so partial writes don't poison the build.
    if output_path.exists() and tmp.read_bytes() == output_path.read_bytes():
        tmp.unlink()
        return
    tmp.replace(output_path)


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description="Embed a binary file as a C++ array")
    p.add_argument("--input", required=True, type=Path)
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--namespace", required=True)
    p.add_argument("--variable", required=True)
    args = p.parse_args(argv)

    if not args.input.is_file():
        print(f"embed_binary: input not found: {args.input}", file=sys.stderr)
        return 2

    emit(args.input, args.output, args.namespace, args.variable)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
